---
api_docs: docs.yaml
api_template_file: template/api/template.mdx
api_template_directory: template/api
template_directory: template/pages
build_directory: docs
api_build_directory: api
api_section_label: API Endpoints
