---
api_docs: docs.yaml
api_template_file: api/template.mdx
api_template_directory: api
template_directory: pages
build_directory: docs
api_build_subdirectory: products/zander/api
api_section_label: API Endpoints
