# This workflow will generate the documentation for zander-docs dynamically

name: Generate documentation

on:
  push:
<<<<<<< HEAD
    branches: [ main ]
  pull_request:
    branches: [ main ]
=======
    branches: [ main, docs ]
  pull_request:
    branches: [ main, docs ]
>>>>>>> 750c6e01af0d423ac779fd900d9486f92d6793aa
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Runs gen.py
      run: python gen.py
